// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: calculate.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CalcServiceClient is the client API for CalcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalcServiceClient interface {
	Sum(ctx context.Context, in *CalcRequest, opts ...grpc.CallOption) (*CalcResponse, error)
	Prime(ctx context.Context, in *PrimeRequest, opts ...grpc.CallOption) (CalcService_PrimeClient, error)
	Avg(ctx context.Context, opts ...grpc.CallOption) (CalcService_AvgClient, error)
	Highest(ctx context.Context, opts ...grpc.CallOption) (CalcService_HighestClient, error)
}

type calcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalcServiceClient(cc grpc.ClientConnInterface) CalcServiceClient {
	return &calcServiceClient{cc}
}

func (c *calcServiceClient) Sum(ctx context.Context, in *CalcRequest, opts ...grpc.CallOption) (*CalcResponse, error) {
	out := new(CalcResponse)
	err := c.cc.Invoke(ctx, "/calculator.CalcService/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calcServiceClient) Prime(ctx context.Context, in *PrimeRequest, opts ...grpc.CallOption) (CalcService_PrimeClient, error) {
	stream, err := c.cc.NewStream(ctx, &CalcService_ServiceDesc.Streams[0], "/calculator.CalcService/Prime", opts...)
	if err != nil {
		return nil, err
	}
	x := &calcServicePrimeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalcService_PrimeClient interface {
	Recv() (*PrimeResponse, error)
	grpc.ClientStream
}

type calcServicePrimeClient struct {
	grpc.ClientStream
}

func (x *calcServicePrimeClient) Recv() (*PrimeResponse, error) {
	m := new(PrimeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calcServiceClient) Avg(ctx context.Context, opts ...grpc.CallOption) (CalcService_AvgClient, error) {
	stream, err := c.cc.NewStream(ctx, &CalcService_ServiceDesc.Streams[1], "/calculator.CalcService/avg", opts...)
	if err != nil {
		return nil, err
	}
	x := &calcServiceAvgClient{stream}
	return x, nil
}

type CalcService_AvgClient interface {
	Send(*AvgRequest) error
	CloseAndRecv() (*AvgResponse, error)
	grpc.ClientStream
}

type calcServiceAvgClient struct {
	grpc.ClientStream
}

func (x *calcServiceAvgClient) Send(m *AvgRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calcServiceAvgClient) CloseAndRecv() (*AvgResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(AvgResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calcServiceClient) Highest(ctx context.Context, opts ...grpc.CallOption) (CalcService_HighestClient, error) {
	stream, err := c.cc.NewStream(ctx, &CalcService_ServiceDesc.Streams[2], "/calculator.CalcService/Highest", opts...)
	if err != nil {
		return nil, err
	}
	x := &calcServiceHighestClient{stream}
	return x, nil
}

type CalcService_HighestClient interface {
	Send(*HighRequest) error
	Recv() (*HighResponse, error)
	grpc.ClientStream
}

type calcServiceHighestClient struct {
	grpc.ClientStream
}

func (x *calcServiceHighestClient) Send(m *HighRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calcServiceHighestClient) Recv() (*HighResponse, error) {
	m := new(HighResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalcServiceServer is the server API for CalcService service.
// All implementations must embed UnimplementedCalcServiceServer
// for forward compatibility
type CalcServiceServer interface {
	Sum(context.Context, *CalcRequest) (*CalcResponse, error)
	Prime(*PrimeRequest, CalcService_PrimeServer) error
	Avg(CalcService_AvgServer) error
	Highest(CalcService_HighestServer) error
	mustEmbedUnimplementedCalcServiceServer()
}

// UnimplementedCalcServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCalcServiceServer struct {
}

func (UnimplementedCalcServiceServer) Sum(context.Context, *CalcRequest) (*CalcResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (UnimplementedCalcServiceServer) Prime(*PrimeRequest, CalcService_PrimeServer) error {
	return status.Errorf(codes.Unimplemented, "method Prime not implemented")
}
func (UnimplementedCalcServiceServer) Avg(CalcService_AvgServer) error {
	return status.Errorf(codes.Unimplemented, "method Avg not implemented")
}
func (UnimplementedCalcServiceServer) Highest(CalcService_HighestServer) error {
	return status.Errorf(codes.Unimplemented, "method Highest not implemented")
}
func (UnimplementedCalcServiceServer) mustEmbedUnimplementedCalcServiceServer() {}

// UnsafeCalcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalcServiceServer will
// result in compilation errors.
type UnsafeCalcServiceServer interface {
	mustEmbedUnimplementedCalcServiceServer()
}

func RegisterCalcServiceServer(s grpc.ServiceRegistrar, srv CalcServiceServer) {
	s.RegisterService(&CalcService_ServiceDesc, srv)
}

func _CalcService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalcServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalcService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalcServiceServer).Sum(ctx, req.(*CalcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalcService_Prime_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalcServiceServer).Prime(m, &calcServicePrimeServer{stream})
}

type CalcService_PrimeServer interface {
	Send(*PrimeResponse) error
	grpc.ServerStream
}

type calcServicePrimeServer struct {
	grpc.ServerStream
}

func (x *calcServicePrimeServer) Send(m *PrimeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CalcService_Avg_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalcServiceServer).Avg(&calcServiceAvgServer{stream})
}

type CalcService_AvgServer interface {
	SendAndClose(*AvgResponse) error
	Recv() (*AvgRequest, error)
	grpc.ServerStream
}

type calcServiceAvgServer struct {
	grpc.ServerStream
}

func (x *calcServiceAvgServer) SendAndClose(m *AvgResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calcServiceAvgServer) Recv() (*AvgRequest, error) {
	m := new(AvgRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CalcService_Highest_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalcServiceServer).Highest(&calcServiceHighestServer{stream})
}

type CalcService_HighestServer interface {
	Send(*HighResponse) error
	Recv() (*HighRequest, error)
	grpc.ServerStream
}

type calcServiceHighestServer struct {
	grpc.ServerStream
}

func (x *calcServiceHighestServer) Send(m *HighResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calcServiceHighestServer) Recv() (*HighRequest, error) {
	m := new(HighRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalcService_ServiceDesc is the grpc.ServiceDesc for CalcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CalcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalcService",
	HandlerType: (*CalcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _CalcService_Sum_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Prime",
			Handler:       _CalcService_Prime_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "avg",
			Handler:       _CalcService_Avg_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Highest",
			Handler:       _CalcService_Highest_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "calculate.proto",
}
